### insert company
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "MMM"
}

### list company
GET http://localhost:8080/company

### search comapy name
GET http://localhost:8080/finance/dividend/3M Company (MMM)

### autocomplete
GET http://localhost:8080/company/autocomplete?keyword=I