### insert company
POST http://localhost:8080/company
Content-Type: application/json
Authorization: Bearer

{
  "ticker": "MMM"
}

### list company
GET http://localhost:8080/company

### search comapy name
GET http://localhost:8080/finance/dividend/3M Company (MMM)1
Authorization: Bearer

### delete comapy name
DELETE http://localhost:8080/company/MMM
Authorization: Bearer

### autocomplete
GET http://localhost:8080/company/autocomplete?keyword=I